package models

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// ID will be generated by system so no pointer for it

type Task struct {
	ID          primitive.ObjectID `bson:"_id"`
	Task        *string            `json:"task"`
}
